<?php

namespace tests\Unit\app\MovieReview;

use App\MovieReview\ClassifiedReview;
use App\MovieReview\Review;
use Tests\TestCase;

class ClassifiedReviewTest extends TestCase
{
    /**
     * @var ClassifiedReview
     */
    protected $classifiedReview;

    /**
     * @var string
     */
    protected $reviewText = 'This is an amazing movie';

    /**
     * @var bool
     */
    protected $isPositiveReview = true;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->classifiedReview = new ClassifiedReview($this->mockReview());
    }

    protected function tearDown()
    {
        unset($this->classifiedReview);

        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    /**
     * @return Review
     */
    protected function mockReview()
    {
        $review = \Mockery::mock(Review::class);

        $review->shouldReceive('setText')->andReturnNull();
        $review->shouldReceive('getText')->andReturn($this->reviewText);

        $review->shouldReceive('setSentiment')->andReturnNull();
        $review->shouldReceive('isPositive')->andReturn($this->isPositiveReview);

        return $review;
    }

    public function testGetReviewMethod()
    {
        $this->assertInstanceOf(
            Review::class,
            $this->classifiedReview->getReview()
        );
    }

    public function testGetAndSetReviewTextMethods()
    {

        $this->classifiedReview->setProvidedReviewText($this->reviewText);

        $this->assertEquals(
            $this->reviewText,
            $this->classifiedReview->getProvidedReviewText()
        );
    }

    public function testPredictedClassProbabilityMethods()
    {
        $this->classifiedReview->setPredictedClass($this->isPositiveReview);

        $this->assertEquals(
            $this->isPositiveReview,
            $this->classifiedReview->isPredictedClassPositive()
        );
    }

    public function testGetSetPredictedProbability()
    {
        $probability = 80.23;

        $this->classifiedReview->setPredictedProbability($probability);

        $this->assertEquals(
            $probability,
            $this->classifiedReview->getPredictedProbability()
        );
    }
}
