<?php

namespace tests\Unit\app\MovieReview;

use App\MovieReview\ClassifiedReview;
use App\MovieReview\Review;
use Tests\TestCase;

class ClassifiedReviewTest extends TestCase
{
    /**
     * @var ClassifiedReview
     */
    protected $classifiedReview;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->classifiedReview = new ClassifiedReview();
    }

    protected function tearDown()
    {
        unset($this->classifiedReview);

        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testGetSetReviewMethods()
    {
        $review = new Review();

        $this->classifiedReview->setReview($review);

        $this->assertEquals($review, $this->classifiedReview->getReview());
    }

    public function testGetSetPredictedProbability()
    {
        $probability = 80.23;

        $this->classifiedReview->setPredictedProbability($probability);

        $this->assertEquals(
            $probability,
            $this->classifiedReview->getPredictedProbability()
        );
    }
}
