<?php

namespace tests\Unit\App\MovieReview;

use App\MovieReview\Review;
use Tests\TestCase;

class ReviewTest extends TestCase
{
    /**
     * @var Review
     */
    protected $model;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->model = new Review();
    }

    protected function tearDown()
    {
        unset($this->model);

        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testGetSetText()
    {
        $review = 'This is a positive review';

        $this->model->setText($review);

        $this->assertEquals($review, $this->model->getText());
    }

    public function testGetSetSentiment()
    {

        $this->model->setSentiment(true);

        $this->assertTrue($this->model->isPositive());
    }
}
